# -*- coding: utf-8 -*-
"""TrainYolo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1elsmgf1VgRT-7Z9a5wdmK9xQBh54VEhE
"""



from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.

# %cd /content
!unzip /content/drive/'My Drive'/'Colab Notebooks'/Yolo/darknet.zip
# %cd /content/darknet

# Commented out IPython magic to ensure Python compatibility.

# %cd /content/darknet
!sudo apt install dos2unix
!dos2unix cfg/yolov3.cfg train.txt val.txt yolo.names yolo.data

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet
!make clean
!make
!chmod +x ./darknet

!rm /content/darknet/backup -r
!ln -s /content/drive/'My Drive'/'Colab Notebooks'/Yolo/backup /content/darknet

# %cd /content/darknet
# !./darknet detector train yolo.data cfg/yolov3.cfg darknet53.conv.74

!./darknet detector train yolo.data cfg/yolov3.cfg backup/yolov3.backup

# !cp "/content/darknet" -r "/content/drive/My Drive/Colab Notebooks/Yolo"

